server.port=8085
spring.application.name=pvp-service

spring.datasource.url=jdbc:h2:file:./data/pvpdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

pvp.battle-service.url=http://localhost:8083
pvp.player-service.url=http://localhost:8081
pvp.party-service.url=http://localhost:8082
